### ISSUE TITLE
plugin does not ignore heredoc indentation

### ISSUE THREAD

**Issue by bastelfreak** [relud/puppet-lint-strict_indent-check#20]
Hi,
in the voxpupuli/puppet-nginx module we've got the following code:

```puppet

class { 'nginx':
  snippets_dir        => '/etc/nginx/snippets',
}

$snippet = @("SNIPPET"/L)
location @custom_451_error {
  return 451;
}
| SNIPPET
```

which produces the following error:

```
examples/snippet.pp:6:strict_indent:FIXED:indent should be 2 chars and is 1
```

I'm not sure if this is easily to fix, at the moment I simply disabled the plugin for those lines.

**Comment by jhoblitt** [comment]
I've run into problems with heredocs as well with `2.0.7`.
```
diff --git a/site/profile/manifests/ccs/autologin.pp b/site/profile/manifests/ccs/autologin.pp
index aae61cf8..d2a666a1 100644
--- a/site/profile/manifests/ccs/autologin.pp
+++ b/site/profile/manifests/ccs/autologin.pp
@@ -13,7 +13,7 @@ class profile::ccs::autologin (Boolean $enable = true) {
       path    => ['/usr/bin'],
       unless  => 'grep -q ^AutomaticLogin /etc/gdm/custom.conf',
       command => @("CMD"/L),
-        sed -i '/^\[daemon.*/a\\
+                sed -i '/^\[daemon.*/a\\
         AutomaticLogin=ccs\n\
         AutomaticLoginEnable=true' /etc/gdm/custom.conf
         | CMD
diff --git a/site/profile/manifests/ccs/daq4.pp b/site/profile/manifests/ccs/daq4.pp
index b42b9525..72c5fd39 100644
--- a/site/profile/manifests/ccs/daq4.pp
+++ b/site/profile/manifests/ccs/daq4.pp
@@ -16,7 +16,7 @@ class profile::ccs::daq4 ($instrument = 'comcam') {
   file { "${dir}/${daq4file}":
     ensure  => file,
     content => @(EOF),
-      export DAQ_HOME=/srv/nfs/lsst-daq/daq-sdk/current/
+                  export DAQ_HOME=/srv/nfs/lsst-daq/daq-sdk/current/
       export LD_LIBRARY_PATH=$DAQ_HOME/x86/lib:$LD_LIBRARY_PATH
       | EOF
     *       => $attributes,
```

**Comment by jhoblitt** [comment]
Note that lint will continue to complain about the heredoc even after an "autofix".

**Comment by yakirgb** [comment]
Facing same bug

**Comment by antenore** [comment]
We are facing something similar.

```
    command => @("EOT"),
      echo "Hello"
      | EOT
```

```
[{
	"resource": "/c:/Users/AntenoreGatta/Documents/Sources/BCC/dev/puppet/modules/puppet/manifests/puppetscripts.pp",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "strict_indent",
	"severity": 4,
	"message": "indent should be 6 chars and is 0",
	"source": "Puppet",
	"startLineNumber": 237,
	"startColumn": 1,
	"endLineNumber": 237,
	"endColumn": 31
}]
```

If I remove the trailing comma, the indentation check passes, and obviously the comma check doesn't (that is normal), but to me, it's because this plugin doesn't properly handle the HEREDOC_OPEN and HEREDOC_POST tokens, setting everything to the same value, when it should handle the trailing comma and eventually other similar cases.

Unfortunately I'm unable to propose a patch at the moment as I should understand more deeply the code... I'm very sorry, but I hope this will help someone else.

For now, I'm disabling strict_indent using the puppet-lint comments (because vscode ignores the file .puppet-lint.rc :-\ )

```
# lint:ignore:strict_indent
command => @("EOT"),
  echo "Hello"
  | EOT
# lint:endignore

**Comment by davidsandilands** [comment]
This generates an error for me
```
  $pg_basebackup = @("PGBASE")
    runuser -u pe-postgres -- \
      /opt/puppetlabs/server/bin/pg_basebackup \
        -D /opt/puppetlabs/server/data/postgresql/${psql_version}/data \
        -d "host=${source_host}
            user=pe-ha-replication
            sslmode=verify-full
            sslcert=/opt/puppetlabs/server/data/pg_certs/_local.cert.pem
            sslkey=/opt/puppetlabs/server/data/pg_certs/_local.private_key.pem
            sslrootcert=/etc/puppetlabs/puppet/ssl/certs/ca.pem"
    | - PGBASE
```
That I haven't been able to find a workaround for.
```
NoMethodError: undefined method `prev_token' for nil:NilClass
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-strict_indent-check-2.1.0/lib/puppet-lint/plugins/check_strict_indent.rb:137:in `block in check'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-strict_indent-check-2.1.0/lib/puppet-lint/plugins/check_strict_indent.rb:49:in `each'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-strict_indent-check-2.1.0/lib/puppet-lint/plugins/check_strict_indent.rb:49:in `check'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-2.5.2/lib/puppet-lint/checkplugin.rb:21:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-2.5.2/lib/puppet-lint/checks.rb:61:in `block in run'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-2.5.2/lib/puppet-lint/checks.rb:58:in `each'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-2.5.2/lib/puppet-lint/checks.rb:58:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-2.5.2/lib/puppet-lint.rb:205:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-2.5.2/lib/puppet-lint/bin.rb:66:in `block in run'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-2.5.2/lib/puppet-lint/bin.rb:62:in `each'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-2.5.2/lib/puppet-lint/bin.rb:62:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/puppet-lint-2.5.2/bin/puppet-lint:7:in `<top (required)>'
/mnt/c/Users/David Sandilands/code/puppetlabs-peadm/bin/puppet-lint:29:in `load'
/mnt/c/Users/David Sandilands/code/puppetlabs-peadm/bin/puppet-lint:29:in `<main>'

**Comment by bassonj** [comment]
I think in the example given the end marker needs to be intended
like this 
```
$snippet = @("SNIPPET"/L)
  location @custom_451_error {
    return 451;
  }
  | SNIPPET
```
refernce: https://www.puppet.com/docs/puppet/6/lang_data_string.html#lang_data_string_heredocs-example

**Comment by bzed** [comment]
Its really sad to see that this bug is 4 years old now and still not fixed.

**Comment by bastelfreak** [comment]
@bzed can you provide a patch for this?

**Comment by paran1** [comment]
In the short term I think the autofix for heredocs should be disabled as it performs obviously incorrect changes. I plan to open a PR for this.

I have also started looking at fixing the indentation properly, but it is tricky given that you have to edit the raw tokens and will take some time.

**Comment by msalway** [comment]
#47 should fix the issues raised in the comments here and the plugin should now correctly calculate the correct indent for heredocs.

Note @bastelfreak your original example won't pass with this which I think is the correct behavior as that heredoc isn't indented.

**Comment by paran1** [comment]
> [@paran1](https://github.com/paran1) any update on this?

I have not had enought time to work on this. I will try to fee up some time once I get back from vacation which is in two weeks. If nothing else I have a handful few extra tests for this that might be useful.

Should at least run the tests with @msalway version to see how that works. But that also have to wait until I am back.
